### ISSUE TITLE
RemoteCollector to Named cache

### ISSUE THREAD

**Issue by gAmUssA** [coherence-community/coherence-demo#1]
hi @brianoliver @tmiddlet2666 

Does coherence support saving the result of stream pipeline to the `NamedCache` e.g. `RemoteCollector.toNamedCache()` or similar.

Thank you

**Comment by brianoliver** [comment]
Hi Viktor (@gAmUssA)

Not sure why Hazelcast is asking this question.   Please don't pollute our issue tracker with product questions.   Use the Oracle Support Forums.

-- Brian

PS: Changing your handle in an attempt to hide the company you work for doesn't work.

**Comment by gAmUssA** [comment]
hi @brianoliver.

I understand your concern. 
I apologize if my comment sent «the wrong message». 
I wasn't trying to hide and troll or something like that. It's not what I do. 
And frankly, that's why I use my personal GH here :)

I was doing some research for my distributed streams presentation.
I didn't want my lack of knowledge of coherence to affect the user impression of your product.
Obviously, I can't possibly know every detail of any product, but I want to make sure I represent it correctly in my comparison. 

I hope this comment clarifies my intention.
Thank you in advance for your understanding and the answer for the original question.
